# -*- coding: utf-8 -*-
#
# FC_REV_A_SPEC documentation build configuration file, created by
# sphinx-quickstart on Sat Dec  7 14:45:15 2013.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os

from sphinx.highlighting import PygmentsBridge
from pygments.formatters.latex import LatexFormatter

class CustomLatexFormatter(LatexFormatter):
    def __init__(self, **options):
        super(CustomLatexFormatter, self).__init__(**options)
        self.verboptions = r"formatcom=\tiny"
        #self.verboptions = r"formatcom=\scriptsize"
        #self.verboptions = r"formatcom=\footnotesize"

PygmentsBridge.latex_formatter = CustomLatexFormatter

breathe_projects = { "doxygen_sim": "../../DeadalusSim/doxygen/DeadalusSim/xml" }
breathe_deafault_project = "doxygen_sim"

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))
#sys.path.append('/home/uspappz/master/SensorFusion/SENSOR_FUSION_SPEC')
#sys.path.append('../../SensorFusion/SENSOR_FUSION_SPEC')
#sys.path.append('../../FC_REV_A/FC_REV_A_SPEC')
#sys.path.append('../../DeadalusSim/DEADALUS_SIM_SPEC')
#sys.path.append('../../GanymedTools/GANYMED_TOOLS_SPEC')
sys.path.append('included_projects/*')
sys.path.append('custom_extensions/bibtex_extension')
bitbucket_project_url = 'http://bitbucket.org/dhellmann/virtualenvwrapper/'

# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Added by nerdomat for breathe support
#sys.path.append( "/home/usappz/breathe-master/breathe/" )
#breathe_projects = { "doxygen_sim": "/home/usappz/GanymedTools/GANYMED_TOOLS_SPEC/doxygen_sim/xml" }
#breathe_deafault_project = "doxygen_sim"

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = ['bibsphinx', 'sphinx.ext.autodoc', 'sphinx.ext.doctest', 'sphinx.ext.intersphinx', 'sphinx.ext.todo', 'sphinx.ext.coverage', 'sphinx.ext.mathjax', 'sphinx.ext.ifconfig', 'sphinx.ext.viewcode', 'sphinxcontrib.bibtex', 'sphinx.ext.numfig']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'MERGE_DOCS_REV_A_SPEC'
copyright = u'2014, Dipl.-Ing. (FH) Andreas Gschoßmann'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.1'
# The full version, including alpha/beta/rc tags.
release = 'master'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'de' 

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []


# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'sphinxdoc'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'MERGE_DOCS_REV_A_SPECdoc'


# -- Options for LaTeX output --------------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
#'papersize': 'letterpaper',

# The font size ('10pt', '11pt' or '12pt').
'pointsize': '11pt',
#'classoptions': ',oneside',

# Additional stuff for the LaTeX preamble.
#'preamble': '\usepackage{biblatex}\\addbibresource{MERGE_DOCS_SPEC.bib}\n\usepackage{extramarks}\n%\usepackage{quotchap}\n\usepackage{epigraph}\n\setcounter{tocdepth}{0}'
'preamble': '\usepackage{acronym}\n%\usepackage[]{thumb}\n%\usepackage{quotchap}\n\usepackage{pdfpages}\n\usepackage{remreset}\n%\usepackage{bibunits}\n\usepackage{extramarks}\n%\usepackage{quotchap}\n\usepackage{epigraph}\n%\setcounter{tocdepth}{0}'
#\usepackage{etoc} in sphinxandi.sty
}

latex_additional_files = [
  'tex_packages/etoc/etoc.sty', 
  'tex_packages/etoc/etoc.dtx', 
  'tex_packages/background/background.sty',
  'tex_packages/background/background.dtx',
  'sphinxandi.cls', 
  'andi.cls',
#  'sphinxandi.sty',
#  'MERGE_DOCS_SPEC.bib',
  'refs.bib',
  'included_projects/rechtliches/RECHTLICHES_SPEC/RECHTLICHES_SPEC.bib',
  'included_projects/rechtliches/RECHTLICHES_SPEC/documents/rechtliches.pdf',

  'included_projects/gps/GPS_SPEC/GPS_SPEC.bib',
  'included_projects/gps/GPS_SPEC/documents/EU_Satellitensystem_Galileo_wird_zwei_Milliarden_teurer-Natur-FOCUS_Online-Nachrichten.pdf',
  'included_projects/gps/GPS_SPEC/documents/GPS-Konkurrent_Galileo-Alles_falsch_gemacht-sueddeutsche.pdf', 
  'included_projects/gps/GPS_SPEC/documents/galileo-satelliten-start.pdf', 
  'included_projects/gps/GPS_SPEC/documents/gps_world_article.pdf', 
  'included_projects/gps/GPS_SPEC/documents/gps_europe.pdf', 
#  'included_projects/DEADALUS_SIM_SPEC/DEADALUS_SIM_SPEC.bib',
#  'included_projects/FC_REV_A_SPEC/FC_REV_A_SPEC.bib',
#  'included_projects/GANYMED_TOOLS_SPEC/GANYMED_TOOLS_SPEC.bib',
#  'included_projects/SENSOR_FUSION_SPEC/SENSOR_FUSION_SPEC.bib',
#  'included_projects/FC_REV_A_SPEC/images/FC_REV_A_SPEC/hw_description_numbers.pdf',
#  'included_projects/FC_REV_A_SPEC/documents/131214_FC_BOM.pdf',
#  'included_projects/FC_REV_A_SPEC/documents/131214_FC_LAYOUT.pdf',
#  'included_projects/FC_REV_A_SPEC/documents/131214_FC_SCHEMATIC.pdf',
#  'images/MERGE_DOCS_SPEC/logo_oth.pdf',
#  'images/MERGE_DOCS_SPEC/download.pdf',
#  'images/MERGE_DOCS_SPEC/mail.pdf',
#  'images/MERGE_DOCS_SPEC/logo_oth_alternativ.pdf',
  'images/MERGE_DOCS_SPEC/sappz.pdf'
]#, 'doxygen/latex/refman.pdf']#, 'images/hw_description_numbers.pdf']

#/home/usappz/master/MergeDocs/MERGE_DOCS_SPEC/included_projects/FC_REV_A_SPEC/documents/131214_FC_BOM.pdf
#/home/usappz/master/MergeDocs/MERGE_DOCS_SPEC/included_projects/FC_REV_A_SPEC/documents/131214_FC_LAYOUT.pdf
#/home/usappz/master/MergeDocs/MERGE_DOCS_SPEC/included_projects/FC_REV_A_SPEC/documents/131214_FC_SCHEMATIC.pdf

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
  ('index', 'MERGE_DOCS_REV_A_SPEC.tex', u'Literaturrecherche',
   u'Dipl.-Ing. (FH) Andreas Gschossmann', 'andi'),
]
# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = 'images/MERGE_DOCS_SPEC/logo_oth.pdf'


# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = ['doxygen/latex/refman.pdf']

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output --------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'merge_docs_rev_a_spec', u'MERGE_DOCS_REV_A Dokumentation',
     [u'Dipl.-Ing. (FH) Andreas Gschossmann'], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output ------------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', 'MERGE_DOCS_REV_A_SPEC', u'MERGE_DOCS_REV_A_SPEC Dokumentation',
   u'Dipl.-Ing. (FH) Andreas Gschossmann', 'FC_REV_A_SPEC', 'One line description of project.',
   'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'


# -- Options for Epub output ---------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = u'MERGE_DOCS_SPEC'
epub_author = u'Dipl.-Ing. (FH) Andreas Gschossmann'
epub_publisher = u'Dipl.-Ing. (FH) Andreas Gschossmann'
epub_copyright = u'2013, Dipl.-Ing. (FH) Andreas Gschossmann'

# The language of the text. It defaults to the language option
# or en if the language is not set.
#epub_language = ''

# The scheme of the identifier. Typical schemes are ISBN or URL.
#epub_scheme = ''

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#epub_identifier = ''

# A unique identification for the text.
#epub_uid = ''

# A tuple containing the cover image and cover page html template filenames.
#epub_cover = ()

# HTML files that should be inserted before the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_pre_files = []

# HTML files shat should be inserted after the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_post_files = []

# A list of files that should not be packed into the epub file.
#epub_exclude_files = []

# The depth of the table of contents in toc.ncx.
#epub_tocdepth = 3 

# Allow duplicate toc entries.
#epub_tocdup = True


# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'http://docs.python.org/': None}
